eureka:
      client:
           register-with-eureka: true
           fetch-registry: true
           service-url: 
               default-zone: http://localhost:8761/eureka/
      instance:
          hostname: localhost
             
uri.dopayment: http://PAYMENT-SERVICE/payment/doPayment
uri.addorder: http://ORDER-SERVICE/order/addOrder
