dopayment: http://PAYMENT-SERVICE/payment/doPayment
addorder: http://ORDER-SERVICE/order/addOrder

test: value from github

eureka:
      client:
           register-with-eureka: true
           fetch-registry: true
           serviceUrl:
               defaultZone: http://localhost:8761/eureka/
      instance:
          hostname: localhost
             
